### PR TITLE
Respect existing TXT records

### LINKED ISSUE #30: Doesn't support validation in multiple regions (Colliding TXT records)
I am validating the same domain (`my.domain.com`) in multiple regions. However, each region tries to create a TXT record for `_amazonses.my.domain.com`. The first stack completes successfully, then the second stack (in another region) fails with the following message:
```
Received response status [FAILED] from custom resource. Message returned: [Tried to create resource record set [name='_amazonses.my.domain.com.', type='TXT'] but it already exists]
```

AWS docs say to create a multi-value TXT record ([here](https://aws.amazon.com/premiumsupport/knowledge-center/ses-verify-domain-accounts-regions/)).

I would be happy to submit a PR to handle the situation when a TXT record already exists, adding another value to the record. Let me know if this would be alright.

### PR DESCRIPTION
**Pull request by joeykilpatrick**
Closes #30

### CODE REVIEW

**Comment by joeykilpatrick** [comment]
@mooyoul Let me know if this needs any changes

File: lambda-packages/dns-validated-domain-identity-handler/src/record.ts [hunk 1]
```diff
@@ -1,20 +1,20 @@
-import { Change } from "aws-sdk/clients/route53";
+import {Change, ResourceRecord} from "aws-sdk/clients/route53";
```
Comment (mooyoul) [inline lambda-packages/dns-validated-domain-identity-handler/src/record.ts:1]: Can you insert space between brackets?

File: lambda-packages/dns-validated-domain-identity-handler/src/record.ts [hunk 2]
```diff
@@ -1,20 +1,20 @@
...
   public static forDKIM(domainName: string, token: string) {
-    return new this(`${token}._domainkey.${domainName}`, "CNAME", `${token}.dkim.amazonses.com`);
+    return new this(`${token}._domainkey.${domainName}`, "CNAME", [{Value: `${token}.dkim.amazonses.com`}]);
   }
 
   public constructor(
     public readonly name: string,
     public readonly type: "CNAME" | "TXT",
-    public readonly value: string,
+    public readonly records: ResourceRecord[],
```
Comment (mooyoul) [inline lambda-packages/dns-validated-domain-identity-handler/src/record.ts:17]: Is there any reason to use `ResourceRecord[]` instead of `string[]`?

**Comment by mooyoul** [comment]
@joeykilpatrick Huge thanks for providing the PR! I just left some comments :)

File: lambda-packages/dns-validated-domain-identity-handler/src/record.ts (hunk 2 above)
Comment (joeykilpatrick) [reply lambda-packages/dns-validated-domain-identity-handler/src/record.ts:17]: When fetching the existing Route53 records, they come back from the API as `ResourceRecord[]`. Instead of unwrapping them to `string[]` just for the constructor to convert them back to  `ResourceRecord[]`, I changed the constructor to work with `ResourceRecord[]` instead. Happy to change it back though if you would like.

File: lambda-packages/dns-validated-domain-identity-handler/src/verifier.ts [hunk 3]
```diff
@@ -30,12 +30,28 @@ export class Verifier {
   ) {}
 
   public async verifyIdentity(upsert: boolean = false) {
+
+    const existingTxtRecord = await this.getCurrentTXTRecord();
+    const values: Route53.ResourceRecord[] = existingTxtRecord?.ResourceRecords || [];
```
Comment (mooyoul) [inline lambda-packages/dns-validated-domain-identity-handler/src/verifier.ts:35]: Then this business logic can be expressed like this:

```ts
    const existingTxtRecord = await this.getCurrentTXTRecord();
    let record: Record;

    if (existingTxtRecord) {
      console.log("Found existing TXT record, adding value to verify domain in zone %s", this.hostedZoneId);

      existingTxtRecord.add(identityToken);
      record = existingTxtRecord;
    } else {
      console.log("Creating a TXT record for verifying domain into zone %s", this.hostedZoneId);

      record = Record.forIdentity(this.domainName, identityToken);
    }
```

File: lambda-packages/dns-validated-domain-identity-handler/src/verifier.ts [hunk 4]
```diff
@@ -30,12 +30,28 @@ export class Verifier {
...
+
+    if (existingTxtRecord) {
+      console.log("Found existing TXT record, adding value to verify domain in zone %s", this.hostedZoneId);
+    } else {
+      console.log("Creating a TXT record for verifying domain into zone %s", this.hostedZoneId);
+    }
+
     const changeId = await this.changeRecords([
-      Record.forIdentity(this.domainName, identityToken).action(upsert ? "UPSERT" : "CREATE"),
+      Record.forIdentity(this.domainName, values).action(existingTxtRecord || upsert ? "UPSERT" : "CREATE"),
```
Comment (mooyoul) [inline lambda-packages/dns-validated-domain-identity-handler/src/verifier.ts:54]: Then

```suggestion
      record.action(existingTxtRecord || upsert ? "UPSERT" : "CREATE"),
```

File: lambda-packages/dns-validated-domain-identity-handler/src/verifier.ts [hunk 5]
```diff
@@ -70,10 +86,24 @@ export class Verifier {
       Identity: this.domainName,
     }).promise();
 
-    console.log("Deleting DNS Records used for domain verification...");
-    await this.changeRecords([
-      Record.forIdentity(this.domainName, identity.token!).action("DELETE"),
-    ]);
+    const existingTxtRecord = await this.getCurrentTXTRecord();
+    const existingTxtValues: Route53.ResourceRecord[] = existingTxtRecord?.ResourceRecords || [];
```
Comment (mooyoul) [inline lambda-packages/dns-validated-domain-identity-handler/src/verifier.ts:90]: Then this business logic can be expressed like this:

```ts
    const record = await this.getCurrentTXTRecord();
    record?.remove(identity.token);

    const recordSize = record?.size ?? 0;

    // If the record contained only the validation value, delete the record.
    // Otherwise just update the record with the value removed.
    if (recordSize === 0) {
      console.log("Deleting DNS Records used for domain verification...");
      await this.changeRecords([
        record.action("DELETE"),
      ]);
    } else {
      console.log("Updating DNS Records to remove the value used for domain verification...");
      await this.changeRecords([
        record.action("UPSERT"),
      ]);
    }
```

File: lambda-packages/dns-validated-domain-identity-handler/src/verifier.ts [hunk 6]
```diff
@@ -155,6 +185,16 @@ export class Verifier {
     };
   }
 
+  private async getCurrentTXTRecord(): Promise<Route53.ResourceRecordSet | undefined> {
+    const res = await this.route53.listResourceRecordSets({
+      HostedZoneId: this.hostedZoneId,
```
Comment (mooyoul) [inline lambda-packages/dns-validated-domain-identity-handler/src/verifier.ts:190]: If you don't want to read entire list, Please supply `StartRecordType` parameter with `TXT` value at least. Someone can have bunch of record sets.

```suggestion
      HostedZoneId: this.hostedZoneId,
      StartRecordType: "TXT",
```

**Review by mooyoul — COMMENTED** [review]
Hello @joeykilpatrick, Sorry for late -  I've been busy for a while 😭 I just left some reviews.
